=== ElearningRet/moodle-local_hub/top/other/SCORM3/themes/theme.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XML Spy v3.0.7 NT (http://www.xmlspy.com)-->
<!ELEMENT theme (parm)+>
<!ELEMENT value (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT label (#PCDATA)>
<!ELEMENT parm (label, description, value)>
<!ATTLIST theme
	name CDATA #REQUIRED
>
<!ATTLIST parm
	id CDATA #REQUIRED
	type CDATA #REQUIRED
>

=== ElearningRet/moodle-local_hub/top/other/SCORM3/themes/outstart/outstart.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE theme SYSTEM "theme.dtd"><theme name="outstart"><parm id="glossaryurl" type="lo"><label>URL for Glossary</label><description>The URL for the LO glossary button.</description><value><![CDATA[undefined]]></value></parm><parm id="showloglossary" type="lo"><label>Show LO Glossary Button</label><description>Show LO Glossary button (true or false)</description><value><![CDATA[true]]></value></parm><parm id="quoteleftimage" type="loimage"><label>Left Quote Image</label><description>Image of a left quote used in Quote content type</description><value><![CDATA[begquote.jpg]]></value></parm><parm id="quoterightimage" type="loimage"><label>Right Quote Image</label><description>Image of a right quote used in Quote content type</description><value><![CDATA[endquote.jpg]]></value></parm><parm id="reviewbuttonimage" type="loimage"><label>Image for Review Button</label><description>Image for review button</description><value><![CDATA[begquote.jpg]]></value></parm><parm id="allowstudentimageupload" type="portal"><label>Student Info Image Upload</label><description>Allow students to upload their own image</description><value><![CDATA[false]]></value></parm><parm id="categoryborders" type="portal"><label>Category Borders</label><description>Boolean value;determines if side borders will be displayed.</description><value><![CDATA[false]]></value></parm><parm id="categorybottom" type="portal"><label>Category Bottom Border</label><description>Accepts graphic or color;creates bottom border for the category.</description><value><![CDATA[FF0000]]></value></parm><parm id="homepagetitle" type="portal"><label>Home Page Title</label><description>Title of portal window (in the title bar of browser)</description><value><![CDATA[E-Learning Portal]]></value></parm><parm id="prescriptionreporton" type="portal"><label>Default Assessment Link</label><description>If set to true, displays prescription page first</description><value><![CDATA[true]]></value></parm><parm id="showstudentsignout" type="portal"><label>Show Student Sign Out</label><description>Change to add or remove the sign out button from the student inf</description><value><![CDATA[true]]></value></parm><parm id="categorybordercolor" type="portalcolor"><label>Category Border Color</label><description>Sets the color for category borders, when border is set to true</description><value><![CDATA[0000FF]]></value></parm><parm id="entrytablecolor" type="portalcolor"><label>Table Color</label><description>Category and table background color</description><value><![CDATA[FFFFFF]]></value></parm><parm id="headercolor" type="portalcolor"><label>Table Header Background Color</label><description>Color of the background color in the header table</description><value><![CDATA[undefined]]></value></parm><parm id="tablecolor" type="portalcolor"><label>Table Body Color</label><description>Table body color</description><value><![CDATA[undefined]]></value></parm><parm id="missingstudentimage" type="portalimage"><label>Missing Student Image</label><description>Image to display if no student image available</description><value><![CDATA[usms200.gif]]></value></parm><parm id="imagecaption_pres" type="presstyle"><label>Image Caption Style - Presentation</label><description>Style for Image content type caption in presentation</description><value><![CDATA[font-size:26pt; font-family: Helvetica]]></value></parm><parm id="lotitle_pres" type="presstyle"><label>Presentation Title Page Style</label><description>Style for presentation title page</description><value><![CDATA[font-size:47pt; font-family: Arial; font-weight:bold; color:#FFFFFF;]]></value></parm><parm id="parameterdesctext_pres" type="presstyle"><label>Parameter Desc Text Style</label><description>Style of Parameter content type description text in presentation</description><value><![CDATA[font-size:21pt; font-family: Helvetica;]]></value></parm><parm id="parametertext_pres" type="presstyle"><label>Parameter Heading Text Style</label><description>Style of Parameter content type text in presentation</description><value><![CDATA[font-family: Helvetica; font-size: 21pt;]]></value></parm><parm id="parametertitle_pres" type="presstyle"><label>Parameter Heading Style</label><description>Style of Parameter content type, title in presentation</description><value><![CDATA[font-size:21pt; font-family: Helvetica; font-weight: bold;]]></value></parm><parm id="smblacktext" type="style"><label>Small Black Text </label><description>Style for text of additional info (ex. TOC)</description><value><![CDATA[color: red; text-decoration: none; font:8pt verdana; vertical-align: top; text-align: left;]]></value></parm><parm id="smbluetext" type="style"><label>Small Blue Text</label><description>Style for bulleted text (ex. TOC)</description><value><![CDATA[color: #000000; text-decoration: none; cursor: hand; font:8pt verdana; font-weight: bold; vertical-align: top;]]></value></parm><parm id="smlefttext" type="style"><label>Small Left Text</label><description>Style for date of last access in Personal Info category</description><value><![CDATA[color: #00ff00; text-decoration: none; cursor: hand; font:9pt verdana; font-weight: bold;vertical-align: top; text-align: left;]]></value></parm><parm id="statustext" type="style"><label>Report Status Style</label><description>Sets the status style of a report header.</description><value><![CDATA[color: #000000; text-decoration: none; font:bold 8pt verdana; vertical-align: top;; text-transform: none; background-color: #CCFFFF]]></value></parm><parm id="tabofftext" type="style"><label>Style for Inactive Tabs</label><description>Sets the font style of inactive tab</description><value><![CDATA[color: white; text-decoration: none; cursor: hand; font: 8pt Arial; font-weight:bold; text-align: center; color: #FFFFFF;]]></value></parm><parm id="tabontext" type="style"><label>Style for Active Tabs</label><description>Sets the font style of active tab</description><value><![CDATA[color: #FFFFFF; font-size:12pt; font-family: Arial; font-weight:bold; text-decoration: none;]]></value></parm></theme>
